# Additional constants for SynWrite API.

MSG_INFO = 0
MSG_WARN = 1
MSG_ERROR = 2
MSG_CONFIRM = -1

CUR_LINE = -1

SEL_NORMAL = 0
SEL_COLUMN = 1
SEL_LINES = 2

LEXER_FOR_FILE = -1
LEXER_FOR_CARET = -2

FILENAME_CURRENT = -1
FILENAME_OPPOSITE = -2
FILENAME_SESSION = -3
FILENAME_PROJECT = -10
FILENAME_PROJECT_MAIN = -11
FILENAME_PROJECT_WORKDIR = -12
FILENAME_PROJECT_SESSION = -13
FILENAME_LEXLIB = -20
FILENAME_PROJECT_BASE = 10000

PROP_NUMS = 1
PROP_EOL = 2
PROP_WRAP = 3
PROP_RO = 4
PROP_MARGIN = 5
PROP_FOLDING = 6
PROP_NON_PRINTED = 7
PROP_TAB_SPACES = 8
PROP_TAB_SIZE = 9
PROP_COL_MARKERS = 10
PROP_TEXT_EXTENT = 11
PROP_ZOOM = 12
PROP_INSERT = 13
PROP_SYNC_RANGES = 14
